### ISSUE TITLE
Typing `ds` in command preview callback moves cursor in commandline 

### ISSUE THREAD

**Issue by smjonas** [kylechui/nvim-surround#95] opened 2022-07-19 10:34 UTC
**Checklist**
- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Describe the bug**
Now that #84 has been solved, I found another issue ^^

**To Reproduce**
Create the following user command, then type `:Test ds`:
```lua
vim.api.nvim_create_user_command("Test", "", { preview =  function(opts, _, _)
  vim.cmd("norm " .. opts.args)
  return 2
end})
```

**Expected behavior**
The cursor should not move in the command line.

![nvim-surround_cmdline_expected](https://user-images.githubusercontent.com/40792180/179730187-5a112213-6adf-4118-8643-ab7b16fe8246.png)

**Actual behavior**
The cursor moves to the very left column in the command line:

![nvim-surround_cmdline](https://user-images.githubusercontent.com/40792180/179730228-13a8eaf0-71e8-4b2b-b3c2-9cb1042d208f.png)

**Additional context**
This causes lots of flickers when typing `dssssssss`. This issue does not occur with a plugin like `vim-sandwich`. So maybe the cursor is moved too early. However, I didn't look at the way cursor positions are handled in the code, so it would be nice if you could clarify a few things here.

This issue does not occur with `ys` btw.

**Comment by kylechui** [comment] 2022-07-19 18:57
Could this perhaps be a 0.8 issue? It seems that `preview` is undefined for v0.7.2

**Comment by kylechui** [comment] 2022-07-19 22:58
I'm still using v0.7.2, so I don't actually know what `preview` does; I'll look into it and give my 2 cents in a bit

**Comment by kylechui** [comment] 2022-07-19 23:03
@smjonas I reckon it has to do with how the built-in `vim.fn.getchar()` function works? Whenever it receives input, the cursor "moves" to the beginning of the command line, even though typing more characters after will "move" the cursor back to the end of the command line (it visually moves, but practically it stays at the end of the command line, if that makes sense).

**Comment by smjonas** [comment] 2022-07-19 23:07
Thank you, seems like we'll have to wait until https://github.com/neovim/neovim/pull/19035 is merged.

**Comment by kylechui** [comment] 2022-07-19 23:08
Glad it's already been found/reported! I'll be closing this as it seems the issue is upstream.

**Closed by kylechui** 2022-07-19 23:08 UTC
Labels: bug
