### ISSUE TITLE
Surrounding a visual selection does not leave the cursor in a consistent position at the end

### ISSUE THREAD

**Issue by alexandreroberts** [kylechui/nvim-surround#216] opened 2023-03-07 20:57 UTC
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.8.3

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```vim
" minconfig.vim

call plug#begin('~/.vim/plugged')
Plug 'kylechui/nvim-surround'
call plug#end()

lua require('nvim-surround').setup()
```

### Sample Buffer

```tex
This |is a| sentence.
```

(Where | indicates the boundaries of a visual selection.)

### Keystroke Sequence

`S]`

### Expected behavior

1. Surround `is a` in square brackets
2. leave the cursor on the opening bracket (or the closing bracket, but certainly one of the two brackets).

### Actual behavior

Step 1 does indeed happen as expected. But then where the cursor ends up depends on *how I made the visual selection*. So if I start with the cursor on the `a` and then type `vbS]`, then the cursor does indeed end up on the opening bracket. But if I start with the cursor on the `i` in `is` then type `vwS]`, the cursor ends up on neither bracket but rather on the `a` (i.e., the place where the cursor was before `nvim-surround` was invoked).

I'm not sure this is strictly speaking a bug; perhaps it is even intentional? But to me the most natural behavior would be to consistently end on the opening bracket (or whatever other thing has surrounded the visual selection).

### Additional context

I am especially interested in making the behavior consistent because I depended on this behavior while using `vim-surround` (from which I recently moved to `nvim-surround`) to write a number of mappings for wrapping visual selection in particular LaTeX commands I use frequently, e.g., `vmap <leader>tq S}i\textquote<ESC>` so that I can time `,tq` to wrap a visual selection in `\textquote{...}`. Now with `nvim-surround`, this produces garbled output.

**Comment by kylechui** [comment] 2023-03-07 21:21
Will work on a fix for this in the next few days; I spent a bit of time working on the same effect for normal-mode surrounds but visual seemed to just slip under my radar.

**Comment by kylechui** [comment] 2023-03-08 04:33
I will note that I have something like this for your use case: https://github.com/kylechui/config.nvim/blob/main/after/ftplugin/tex.lua#L28

It just enables `c`ommand surrounds

**Comment by kylechui** [comment] 2023-03-08 04:38
Please update to the latest commit and see if the issue is resolved; let me know how it goes!

**Comment by alexandreroberts** [comment] 2023-03-08 16:18
It works perfectly now. Thanks so much for the fix!

**Comment by alexandreroberts** [comment] 2023-03-08 16:20
> I will note that I have something like this for your use case: https://github.com/kylechui/config.nvim/blob/main/after/ftplugin/tex.lua#L28
> 
> It just enables `c`ommand surrounds

Yes, I've been using this feature, it's great. But `Sctextquote` takes longer to write than `,tq`. Is there some simple way to harness this `c` option to write a more intelligent mapping for `,tq` (i.e., that has the same effect but simply inputs `textquote` to the `c` option directly rather than prompting the user)?

**Comment by kylechui** [comment] 2023-03-08 18:02
Change the `add` key to be ```lua
add = { "\\textquote{", "}" }
```
See the help menu for more information.

**Comment by alexandreroberts** [comment] 2023-03-08 20:18
Ah! That makes sense. Sorry for the elementary question; as you can tell, my understanding of the code is very limited, especially in lua. Hopefully I am learning...

**Closed** 2023-03-08 20:18 UTC
Labels: bug

**Comment by kylechui** [comment] 2023-03-08 20:19
No worries, feel free to tag me here (or perhaps in a discussions post) if you have any more questions about the plugin or Lua in general!

**Comment by alexandreroberts** [comment] 2023-03-08 20:26
Thank you, much appreciated!
