### ISSUE TITLE
Several targets like (, { and < don't work when kitty keyboard protocol is enabled

### ISSUE THREAD

**Issue by craigmac** [kylechui/nvim-surround#200] opened 2023-01-18 21:27 UTC
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

HEAD

### Plugin Version

Tagged (Stable)

### Minimal Configuration

nvim --clean

### Sample Buffer

function

### Keystroke Sequence

ysiw(

### Expected behavior

(function)

### Actual behavior

function

### Additional context

Need to have a terminal emulator with kitty keyboard protocol turned on.

Wezterm reports `(` as `<S-(>` and `[` as `<S-[>` along with the others: `<S-lt>`, `<S->>`

**Comment by kylechui** [comment] 2023-02-09 06:59
I'm afraid I don't really know what the Kitty protocol is, nor how to replicate this issue. Perhaps try using the untagged version of this plugin, and see if that resolves things?

**Comment by craigmac** [comment] 2023-02-09 14:23
Open wezterm and set [`enable_kitty_protocol = true`]((https://wezfurlong.org/wezterm/config/key-encoding.html)) in the wezterm [config file](https://wezfurlong.org/wezterm/config/files.html) then just follow the steps listed. Untagged version didn't resolve things.

**Comment by kylechui** [comment] 2023-02-09 17:45
This seems like it would be an issue on Wezterm's side(?); what happens when you go in insert mode and hit `<C-v>(`? Does it just show `(` or something like `<S-(>` (former is correct)? The plugin should do the correct thing if given the correct inputs, but I'm not familiar with wezterm nor how it handles key inputs.

**Comment by craigmac** [comment] 2023-02-09 20:47
Both wezterm (with kitty kbd protocol enabled) and actually kitty terminal both show `<S-(>`. It's not that one is more correct than the other, what I'm saying is shift numbers keys are all going to have this issue with your plugin because you don't _also_ map `<S-(>`. I think just a simple map from `<S-(>` to `(` would support the protocol and still leave support for non-users of the kitty kbd protocol intact.

**Comment by kylechui** [comment] 2023-02-10 19:54
I just downloaded wezterm on my own computer and was able to replicate the issue, although on a friend's Macbook it just shows `(` and `)`, which is strange. Is it intended behavior for the keys to be represented as `<S-(>`?

**Comment by craigmac** [comment] 2023-02-11 00:30
my mistake, you are right I had assumed kitty would be the same as wezterm is supposedly using that protocol. I'm not sure why or how they are differing. I'll mention this in wezterm issues and see why `*` is seen as two different things.

**Comment by kylechui** [comment] 2023-04-17 03:03
Closing this issue since [it seems to have been fixed upstream](https://github.com/wez/wezterm/issues/2546).

**Closed by kylechui** 2023-04-17 03:03 UTC
Labels: bug, upstream issue
